### ISSUE TITLE
Does this blog have a template?

### ISSUE THREAD

**Issue by singularityDLW** [Eliran-Turgeman/eliran-turgeman.github.io#1]
Hi Eliran,

Very nice to meet u, This is not an issue actually. I just read your article about Software modularity. Its a very good one and gave me so much thought. But now I really wonder that do u use a template in your blog? I really like your design style.

**Comment by Eliran-Turgeman** [comment]
Hi @singularityDLW  :)
I used a template called cactus 

https://github.com/probberechts/hexo-theme-cactus
